### PR TITLE
fix(ci_node_10) updated npm version to last working version [#78]

### PR DESCRIPTION
**Pull request by farnk05**
# Description
This adds a fixed version of npm since the latest version seems to flag a non support for node 10. 

---
# Issue
Proposed fix for issue #78.

### CODE REVIEW

**Review by weekens — APPROVED** [review]

**Comment by weekens** [comment]
Hi! Thanks for you PR! I'll still need to update Travis configuration, which apparently became outdated.

**Comment by farnk05** [comment]
Can I help add to this PR to fix that up?  I'd love to help contribute to this project.  I've worked with Akka in the past, and I'd love to help add a few tools from akka here.

**Comment by weekens** [comment]
> Can I help add to this PR to fix that up? I'd love to help contribute to this project. I've worked with Akka in the past, and I'd love to help add a few tools from akka here.

Sure! Any help is welcome!

**Comment by weekens** [comment]
Unfortunately, I cannot recover Travis - it now asks me to choose a billing plan and enter the billing information. I will have to disable Travis for now and look for some other CI with Linux container.

**Comment by weekens** [comment]
Thanks for your MR! Looking forward for further collaboration!

**Pull request merged**
